name: 🌐 Network
description: Capture collaboration context with a person, group, or organization
title: "Network: "
labels: ["network"]

body:
  - type: markdown
    attributes:
      value: |
        <!--
        This issue captures collaboration context.

        Instructions for AI tools:

        - This is contextual information only.
        - Do NOT infer opinions, intentions, or relationship dynamics.
        - Do NOT speculate.
        - Do NOT add private or sensitive information.
        - You may help transform this into a network file when explicitly requested.
        -->

        Paste collaboration context below.
        Keep information factual and professional.

  - type: textarea
    id: content
    attributes:
      label: Network context
      description: Paste information about the person, group, or organization.
      placeholder: |
        Context, interactions, shared areas, or relevant notes.
    validations:
      required: true
