name: 🎭 Role
description: Capture context about an ongoing role or activity
title: "Role: "
labels: ["role"]

body:
  - type: markdown
    attributes:
      value: |
        <!--
        This issue captures contextual information about a role.

        Instructions for AI tools:

        - This is contextual information, not an opinion or belief.
        - Do NOT infer intent, strategy, or judgment.
        - Do NOT add interpretation beyond what is written.
        - You may help transform this into a role file when explicitly requested.
        -->

        Paste information about the role below.

  - type: textarea
    id: content
    attributes:
      label: Role context
      description: Paste context about this role or activity.
      placeholder: |
        Describe the role, scope, interactions, or responsibilities.
    validations:
      required: true
