name: 🌱 Seed
description: Capture a raw idea, question, or intuition
title: "Seed: "
labels: ["seed"]

body:
  - type: markdown
    attributes:
      value: |
        <!--
        This issue captures a raw seed.

        Instructions for AI tools:

        - This is NOT a task to solve.
        - Do NOT expand or resolve the idea unless explicitly asked.
        - Do NOT promote this seed into an understanding automatically.
        - Preserve the original wording and intent.
        - You may help clarify or reformat only when requested.
        -->

        Paste the seed below.
        Raw, incomplete, or messy content is expected.

  - type: textarea
    id: content
    attributes:
      label: Seed content
      description: Paste the idea, note, or thought here.
      placeholder: |
        Paste anything here.
        Fragments and half-formed thoughts are fine.
    validations:
      required: true
