name: 🧠 Understanding
description: Capture an evolving understanding for the cortex
title: "Understanding: "
labels: ["understanding"]

body:
  - type: markdown
    attributes:
      value: |
        <!--
        This issue represents an evolving understanding.

        Instructions for AI tools (Copilot, agents):

        - This is NOT a task and should not be solved.
        - Do NOT add conclusions, opinions, or new reasoning.
        - Do NOT rewrite content unless explicitly asked.
        - Preserve the author's meaning and voice.
        - When explicitly requested, you MAY transform this content into a markdown understanding file.
        - Otherwise, treat this issue as a thinking artifact only.
        -->

        Paste the full understanding below.
        This may include summary, current understanding, context, notes, or any structure generated elsewhere.

  - type: textarea
    id: content
    attributes:
      label: Understanding content
      description: Paste the full understanding here (AI-generated or written by you).
      placeholder: |
        Paste everything here.
        No need to split into sections or fields.
    validations:
      required: true
